export type AtlasLevel = 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9 | 10 | 11 | 12

export type AtlasNodeKind =
  | 'focus'
  | 'factor'
  | 'state'
  | 'trajectory'
  | 'rule'
  | 'framework'
  | 'observer'
  | 'model'
  | 'architecture'
  | 'system'
  | 'axis'

export interface AtlasNode {
  id: string
  label: string
  x: number
  y: number
  stage: number
  kind: AtlasNodeKind
  explanation: string
}

export interface AtlasEdge {
  from: string
  to: string
  label: string
  stage: number
  tension?: boolean
  bidirectional?: boolean
  explanation: string
}

export interface LifePurposeAtlasMap {
  level: AtlasLevel
  title: string
  thesis: string
  blindSpot: string
  leap: string
  question: string
  stages: string[]
  insights: string[]
  nodes: AtlasNode[]
  edges: AtlasEdge[]
}

const n = (
  id: string,
  label: string,
  x: number,
  y: number,
  stage: number,
  kind: AtlasNodeKind,
  explanation: string,
): AtlasNode => ({ id, label, x, y, stage, kind, explanation })

const e = (
  from: string,
  to: string,
  label: string,
  stage: number,
  explanation: string,
  options: Pick<AtlasEdge, 'tension' | 'bidirectional'> = {},
): AtlasEdge => ({ from, to, label, stage, explanation, ...options })

export const LIFE_PURPOSE_ATLAS: LifePurposeAtlasMap[] = [
  {
    level: 1,
    title: 'Life Purpose as a precise present hypothesis',
    thesis: 'Before connecting life purpose to anything else, make the phenomenon itself precise enough that later relationships have something stable to refer to.',
    blindSpot: 'Ordinary reflection often starts with vague phrases such as “find my calling”. A vague centre contaminates every later branch.',
    leap: '1D reasoning deliberately isolates one object. The advance is precision, not complexity.',
    question: 'What exactly do I mean by “life purpose” before I explain what causes it, fulfils it or changes it?',
    stages: ['Name the phenomenon', 'Define its boundary', 'Describe its present state', 'Anchor it to observable evidence'],
    insights: [
      'Working definition: a revisable organising direction that makes effort, identity and contribution feel worth coordinating over time.',
      'Boundary: purpose is not identical to a job, mood, status, one goal, pleasure or certainty about destiny.',
      'Present state: “I currently experience purpose most strongly when learning difficult things and turning them into something useful for others.”',
      'Evidence anchor: repeated voluntary return to the activity, sustained energy after difficulty, and behaviour that persists without external praise.',
    ],
    nodes: [
      n('purpose', 'LIFE PURPOSE', 550, 330, 1, 'focus', 'The single object being stabilised. In 1D, do not branch yet: define, bound and observe it.'),
    ],
    edges: [],
  },
  {
    level: 2,
    title: 'Life Purpose as a field of direct relationships',
    thesis: 'Now connect Life Purpose to other concepts one pair at a time and state the exact semantic relationship on every line.',
    blindSpot: 'A list of “things important to me” is not yet relational reasoning. The line itself must say what one thing does to another.',
    leap: '2D turns an isolated concept into explicit pairwise propositions that can be challenged, compared and communicated.',
    question: 'What directly shapes, supports, constrains, expresses or results from my current sense of purpose?',
    stages: ['Add inward influences', 'Add outward effects', 'Add dependencies', 'Add revealing contrasts'],
    insights: [
      'Values influence which sacrifices still feel worthwhile.',
      'Strengths affect which forms of contribution are sustainable rather than merely admirable.',
      'Purpose can increase persistence, while exhaustion can weaken access to purpose without disproving it.',
      'Meaningful contribution contrasts with prestige when prestige produces recognition without felt significance.',
    ],
    nodes: [
      n('purpose', 'Life Purpose', 550, 330, 1, 'focus', 'The focal phenomenon.'),
      n('values', 'Values', 165, 115, 1, 'factor', 'Enduring preferences about what deserves care, protection or sacrifice.'),
      n('strengths', 'Strengths', 165, 265, 1, 'factor', 'Capacities that affect which contributions can be sustained and developed.'),
      n('experience', 'Life Experience', 165, 420, 1, 'factor', 'Repeated experiences teach what feels alive, intolerable, possible and important.'),
      n('needs', 'Human Needs', 165, 565, 2, 'factor', 'Autonomy, competence, belonging, security and related needs condition purpose.'),
      n('action', 'Chosen Action', 925, 120, 2, 'factor', 'Purpose becomes behaviour through priorities and repeated commitments.'),
      n('persistence', 'Persistence', 925, 255, 2, 'state', 'A coherent reason for effort can increase endurance through difficulty.'),
      n('contribution', 'Contribution', 925, 390, 2, 'factor', 'Purpose often points beyond the self toward beneficiaries or valued systems.'),
      n('resources', 'Resources', 925, 535, 3, 'factor', 'Time, money, health and access condition which purpose expressions are viable.'),
      n('prestige', 'Prestige', 550, 600, 4, 'factor', 'Status can overlap with purpose but is not evidence that an activity is meaningful.'),
      n('pleasure', 'Immediate Pleasure', 550, 80, 4, 'state', 'Pleasure may accompany purpose, but purpose can also require discomfort and delay.'),
    ],
    edges: [
      e('values', 'purpose', 'shapes', 1, 'Values bias which directions feel morally and emotionally significant.'),
      e('strengths', 'purpose', 'channels', 1, 'Strengths influence the forms through which purpose can be expressed.'),
      e('experience', 'purpose', 'calibrates', 1, 'Experience updates what the person believes is worth devoting life to.'),
      e('needs', 'purpose', 'supports access to', 2, 'Chronically unmet needs can distort or crowd out purpose exploration.'),
      e('purpose', 'action', 'prioritises', 2, 'Purpose changes which actions receive scarce time and attention.'),
      e('purpose', 'persistence', 'can increase', 2, 'Meaning can make difficult effort more tolerable.'),
      e('purpose', 'contribution', 'seeks expression through', 2, 'Purpose often becomes concrete through effects on others or valued systems.'),
      e('purpose', 'resources', 'depends partly on', 3, 'A purpose expression must coexist with physical and economic constraints.'),
      e('purpose', 'prestige', 'is not equivalent to', 4, 'High status and high purpose can diverge sharply.', { tension: true, bidirectional: true }),
      e('purpose', 'pleasure', 'is not reducible to', 4, 'Purpose can contain sacrifice, uncertainty and delayed reward.', { tension: true, bidirectional: true }),
    ],
  },
  {
    level: 3,
    title: 'Life Purpose as an interacting system',
    thesis: 'Stop treating each influence independently. Model the network that jointly produces, suppresses and recalibrates experienced purpose.',
    blindSpot: 'A radial map where every node only touches Life Purpose still hides mechanisms. Systems reasoning requires factors to affect one another.',
    leap: '3D introduces mediation, moderation, constraints, competing forces and non-central cross-links. Purpose becomes an emergent system state.',
    question: 'How do identity, feedback, relationships, opportunity, competence and constraints interact to generate my present pattern of purpose?',
    stages: ['Build the core system', 'Insert mechanisms', 'Add pressures and constraints', 'Cross-link the network'],
    insights: [
      'Values do not become purpose directly: perceived opportunity and self-efficacy often mediate translation into action.',
      'Competence can create better feedback, which strengthens identity, which increases willingness to attempt harder contribution.',
      'Financial pressure can change the effect of autonomy: freedom without resources may increase anxiety rather than purpose.',
      'Belonging can moderate risk-taking—supportive relationships make exploratory identity changes less threatening.',
    ],
    nodes: [
      n('purpose', 'Experienced Purpose', 550, 340, 1, 'focus', 'A system-level state produced by interactions rather than one isolated cause.'),
      n('values', 'Values', 140, 105, 1, 'factor', 'What the person considers worth caring about.'),
      n('identity', 'Identity', 550, 100, 1, 'state', 'The current model of “who I am” and what roles feel self-consistent.'),
      n('needs', 'Needs', 960, 105, 1, 'factor', 'Autonomy, belonging, competence, security and related needs.'),
      n('opportunity', 'Opportunity', 150, 340, 1, 'factor', 'Available contexts where values can become behaviour.'),
      n('action', 'Action / Practice', 550, 590, 1, 'factor', 'Repeated behaviour through which a purpose hypothesis is tested.'),
      n('impact', 'Real-world Impact', 950, 340, 1, 'factor', 'Observable consequences for beneficiaries or systems.'),
      n('feedback', 'Feedback', 830, 565, 2, 'factor', 'Signals about competence, usefulness, fit and unintended consequences.'),
      n('selfeff', 'Self-efficacy', 320, 565, 2, 'state', 'Belief that effort can produce meaningful effects.'),
      n('belonging', 'Belonging', 780, 205, 2, 'factor', 'Social support changes the emotional cost of experimentation.'),
      n('money', 'Economic Pressure', 300, 205, 3, 'factor', 'Resource pressure can narrow the option space and alter risk tolerance.'),
      n('health', 'Energy / Health', 1000, 520, 3, 'factor', 'Embodied capacity limits the amount and type of sustained contribution.'),
      n('status', 'Status Incentives', 550, 210, 3, 'factor', 'External rewards can amplify or distort signals of genuine purpose.'),
      n('learning', 'Learning', 310, 430, 4, 'factor', 'Experience can alter both skill and interpretation of what matters.'),
      n('relationships', 'Relationships', 800, 430, 4, 'factor', 'Close others co-shape commitments, obligations and possible identities.'),
    ],
    edges: [
      e('values', 'identity', 'helps organise', 1, 'Values become part of the story the person tells about self.'),
      e('identity', 'purpose', 'frames', 1, 'Identity filters which directions feel “for someone like me”.'),
      e('opportunity', 'action', 'enables', 1, 'Purpose cannot be tested without contexts for action.'),
      e('action', 'impact', 'produces', 1, 'Behaviour creates actual consequences rather than imagined purpose.'),
      e('impact', 'purpose', 'grounds', 1, 'Observed usefulness can strengthen or challenge the purpose hypothesis.'),
      e('needs', 'belonging', 'includes', 2, 'Belonging is one human need relevant to sustained purpose.'),
      e('belonging', 'action', 'moderates risk in', 2, 'Support can make experimentation safer.'),
      e('action', 'feedback', 'generates', 2, 'Action returns evidence.'),
      e('feedback', 'selfeff', 'calibrates', 2, 'Feedback changes perceived capability.'),
      e('selfeff', 'action', 'amplifies willingness for', 2, 'Higher efficacy can support harder experiments.'),
      e('money', 'opportunity', 'constrains', 3, 'Economic pressure removes or delays options.'),
      e('health', 'action', 'limits sustainable', 3, 'Physical capacity changes what can be repeated.'),
      e('status', 'identity', 'rewards certain versions of', 3, 'Status can make externally rewarded identities unusually sticky.'),
      e('status', 'purpose', 'can masquerade as', 3, 'Recognition may be misread as meaning.', { tension: true }),
      e('action', 'learning', 'creates', 4, 'Practice generates new knowledge about self and world.'),
      e('learning', 'values', 'can refine', 4, 'New experience can change what the person values.'),
      e('relationships', 'identity', 'co-author', 4, 'Identity is partly relational.'),
      e('impact', 'relationships', 'changes', 4, 'Consequences of a purpose pursuit feed back into social relationships.'),
    ],
  },
  {
    level: 4,
    title: 'Life Purpose as a self-transforming temporal loop',
    thesis: 'The map now has to move. Purpose changes choices; choices create experiences; experiences reconstruct identity; the reconstructed self interprets purpose differently.',
    blindSpot: 'A 3D system can still be frozen in one state. Adding dates is not enough unless the relationships themselves transform.',
    leap: '4D represents sequence, delay, path-dependence and closed recursive feedback. The seeker is changed by the search.',
    question: 'How does pursuing a purpose today create the future person who will later redefine what purpose means?',
    stages: ['Map the starting state', 'Map transformation through action', 'Add delayed consequences', 'Close the feedback loop'],
    insights: [
      'A purpose hypothesis is partly self-creating: choosing a direction builds skills and relationships that make that direction more plausible later.',
      'Short-term relief can produce long-term purpose loss—for example, avoiding uncertainty protects identity now but prevents evidence that could expand it.',
      'Success can invalidate the original goal: achieving status may reveal that status was only a proxy for autonomy or contribution.',
      'Purpose should therefore be periodically re-authored, not merely pursued harder.',
    ],
    nodes: [
      n('self0', 'Present Self', 120, 345, 1, 'state', 'Current identity, constraints, values and beliefs about possible futures.'),
      n('hypothesis', 'Purpose Hypothesis v1', 300, 180, 1, 'state', 'The current best guess about an organising life direction.'),
      n('choice', 'Commitment', 475, 180, 2, 'factor', 'A choice that allocates real time or reputation to the hypothesis.'),
      n('practice', 'Repeated Practice', 650, 180, 2, 'factor', 'Repeated behaviour alters skill, environment and social identity.'),
      n('outcome', 'Consequences', 830, 180, 2, 'state', 'Actual effects: competence, impact, costs, relationships and emotions.'),
      n('feedback', 'Feedback', 990, 345, 2, 'factor', 'Evidence about whether the hypothesis works and for whom.'),
      n('delay', 'Delayed Costs', 830, 535, 3, 'state', 'Burnout, foregone options or relationship effects may arrive much later.'),
      n('skills', 'New Capabilities', 650, 535, 3, 'state', 'Practice changes what the person can do next.'),
      n('identity2', 'Identity v2', 475, 535, 3, 'state', 'The self-model after living through the path.'),
      n('purpose2', 'Purpose Hypothesis v2', 300, 535, 4, 'state', 'Purpose re-authored after evidence and identity transformation.'),
      n('future', 'Future Self', 120, 535, 4, 'state', 'The person produced by the trajectory, not merely the present self later in time.'),
      n('avoid', 'Avoidance Loop', 550, 350, 4, 'state', 'An alternative loop: uncertainty → avoidance → no evidence → continued uncertainty.'),
    ],
    edges: [
      e('self0', 'hypothesis', 'constructs', 1, 'The present self generates a purpose hypothesis from current models.'),
      e('hypothesis', 'choice', 'guides', 2, 'Purpose affects which commitments are made.'),
      e('choice', 'practice', 'becomes', 2, 'Commitment must become repeated action to create information.'),
      e('practice', 'outcome', 'produces', 2, 'Practice creates consequences.'),
      e('outcome', 'feedback', 'is interpreted as', 2, 'Consequences become feedback only when noticed and interpreted.'),
      e('outcome', 'delay', 'also creates', 3, 'Some effects are temporally displaced.'),
      e('practice', 'skills', 'builds', 3, 'Repeated practice changes capability.'),
      e('skills', 'identity2', 'changes evidence for', 3, 'New ability changes which identities feel credible.'),
      e('delay', 'identity2', 'can revise', 3, 'Delayed costs can change the meaning of an earlier success.'),
      e('feedback', 'identity2', 'updates', 3, 'Feedback alters the self-model.'),
      e('identity2', 'purpose2', 'reinterprets', 4, 'A changed self asks a different purpose question.'),
      e('purpose2', 'future', 'organises', 4, 'New purpose shapes the next stage of life.'),
      e('future', 'self0', 'would advise', 4, 'Future-self perspective recursively changes present interpretation.', { bidirectional: true }),
      e('purpose2', 'hypothesis', 'revises', 4, 'The later model closes the learning loop by changing the earlier rule.'),
      e('hypothesis', 'avoid', 'can trigger uncertainty →', 4, 'Purpose uncertainty can trigger avoidance.'),
      e('avoid', 'hypothesis', 'preserves uncertainty in', 4, 'Avoidance prevents corrective evidence, closing a harmful loop.', { tension: true }),
    ],
  },
  {
    level: 5,
    title: 'Life Purpose as a space of possible lives',
    thesis: 'Hold several plausible 4D trajectories at once. The object is no longer “the future”; it is the branching landscape of futures and the conditions that select among them.',
    blindSpot: '4D can follow transformation but still privilege one storyline. Strategy requires comparing mutually exclusive paths before they are lived.',
    leap: '5D adds counterfactual trajectories, branch conditions, convergence, option value and irreversible thresholds.',
    question: 'Which different people could I become from the same present, and which early choices create the largest divergence?',
    stages: ['Define the common present', 'Generate genuinely different futures', 'Name branch conditions', 'Map convergence and irreversibility'],
    insights: [
      'Several lives can express the same underlying value through different structures; purpose need not have one occupational answer.',
      'The best early move may maximise learning and option value rather than commit to the apparently best destination.',
      'Some choices are reversible experiments; others create identity, financial or family commitments that make later switching expensive.',
      'A robust purpose may be the invariant that survives across several futures, not the label of one future.',
    ],
    nodes: [
      n('present', 'Present Self', 550, 80, 1, 'focus', 'The shared branch point from which several futures are considered.'),
      n('experiment', '12-month Experiment', 550, 205, 1, 'factor', 'A reversible probe designed to generate information before major commitment.'),
      n('heal', 'Clinical / Healing Path', 135, 390, 2, 'trajectory', 'A future organised around direct care and reducing suffering.'),
      n('build', 'Builder / Entrepreneur Path', 345, 390, 2, 'trajectory', 'A future organised around creating systems, products or institutions.'),
      n('teach', 'Teacher / Scholar Path', 550, 390, 2, 'trajectory', 'A future organised around understanding and transferring knowledge.'),
      n('community', 'Family / Community Path', 755, 390, 2, 'trajectory', 'A future that places relational stewardship near the centre.'),
      n('steward', 'Ecological Stewardship Path', 965, 390, 2, 'trajectory', 'A future organised around protecting long-horizon living systems.'),
      n('condition1', 'Direct human contact energises', 135, 565, 3, 'factor', 'Evidence favouring the healing trajectory.'),
      n('condition2', 'Leverage & creation energise', 345, 565, 3, 'factor', 'Evidence favouring the builder trajectory.'),
      n('condition3', 'Deep inquiry remains compelling', 550, 565, 3, 'factor', 'Evidence favouring the scholar trajectory.'),
      n('condition4', 'Relational responsibility dominates', 755, 565, 3, 'factor', 'Evidence favouring the community trajectory.'),
      n('condition5', 'Planetary scale matters most', 965, 565, 3, 'factor', 'Evidence favouring ecological stewardship.'),
      n('invariant', 'Invariant: develop capability → contribute meaningfully', 550, 690, 4, 'trajectory', 'A deeper purpose structure that can survive across outwardly different lives.'),
      n('threshold', 'Irreversible Thresholds', 880, 205, 4, 'factor', 'Debt, geography, dependants, public identity or credential commitments can close options.'),
      n('option', 'Option Value', 220, 205, 4, 'factor', 'Some experiments are valuable because they preserve multiple futures while increasing information.'),
      n('regret', 'Regret Test', 350, 690, 4, 'factor', 'Compare future regret from action, inaction and delayed commitment rather than asking which choice is risk-free.'),
    ],
    edges: [
      e('present', 'experiment', 'tests itself through', 1, 'The present self creates information rather than only imagining futures.'),
      e('experiment', 'heal', 'could branch into', 2, 'One possible future.'),
      e('experiment', 'build', 'could branch into', 2, 'One possible future.'),
      e('experiment', 'teach', 'could branch into', 2, 'One possible future.'),
      e('experiment', 'community', 'could branch into', 2, 'One possible future.'),
      e('experiment', 'steward', 'could branch into', 2, 'One possible future.'),
      e('heal', 'condition1', 'gains probability if', 3, 'The branch should depend on evidence, not fantasy.'),
      e('build', 'condition2', 'gains probability if', 3, 'Branch condition.'),
      e('teach', 'condition3', 'gains probability if', 3, 'Branch condition.'),
      e('community', 'condition4', 'gains probability if', 3, 'Branch condition.'),
      e('steward', 'condition5', 'gains probability if', 3, 'Branch condition.'),
      e('option', 'experiment', 'favours', 4, 'Reversible probes preserve learning capacity.'),
      e('threshold', 'heal', 'can lock in', 4, 'Training and institutional commitments can become costly to reverse.'),
      e('threshold', 'build', 'can lock in', 4, 'Capital and reputation can create path dependence.'),
      e('heal', 'invariant', 'may express', 4, 'Different lives can converge on a deeper purpose.'),
      e('build', 'invariant', 'may express', 4, 'Different lives can converge on a deeper purpose.'),
      e('teach', 'invariant', 'may express', 4, 'Different lives can converge on a deeper purpose.'),
      e('community', 'invariant', 'may express', 4, 'Different lives can converge on a deeper purpose.'),
      e('steward', 'invariant', 'may express', 4, 'Different lives can converge on a deeper purpose.'),
      e('regret', 'present', 'reframes decision for', 4, 'Counterfactual regret changes how the current branch point is evaluated.'),
    ],
  },
  {
    level: 6,
    title: 'Life Purpose as an output of hidden generative rules',
    thesis: 'Move above the visible futures. Ask what assumptions, reward functions, prohibitions and definitions generated those futures as “the options” in the first place.',
    blindSpot: '5D can compare many futures while silently accepting the same cultural rules that generated every one of them.',
    leap: '6D changes the possibility generator. Instead of choosing the best path, expose and alter the rules that make paths appear valuable, shameful, realistic or invisible.',
    question: 'What hidden rules are generating the life purposes I currently believe I am allowed to have?',
    stages: ['Separate visible futures from generators', 'Expose assumptions', 'Expose objective functions and prohibitions', 'Rewrite a generator and regenerate futures'],
    insights: [
      '“Purpose must be one career” generates unnecessary identity foreclosure. Replacing it with “purpose can be a portfolio” creates previously invisible combinations.',
      '“My worth must be proven” can make status-heavy futures feel meaningful even when the true objective function is avoidance of shame.',
      '“Security before aliveness” can indefinitely postpone exploration because security has no natural completion point.',
      'Changing one generative rule can reorganise the entire 5D future landscape without choosing any future directly.',
    ],
    nodes: [
      n('visible', 'VISIBLE FUTURES', 550, 85, 1, 'focus', 'The trajectories that currently appear thinkable.'),
      n('career', 'One coherent career', 220, 205, 1, 'trajectory', 'A conventional visible option.'),
      n('portfolio', 'Portfolio life', 430, 205, 1, 'trajectory', 'A mixed expression across work, service, relationships and learning.'),
      n('service', 'Service-centred life', 670, 205, 1, 'trajectory', 'A trajectory optimising contribution.'),
      n('explore', 'Experimental life', 890, 205, 1, 'trajectory', 'A trajectory optimising discovery and option value.'),
      n('assume1', 'Purpose must be ONE thing', 150, 430, 2, 'rule', 'A hidden definition that collapses portfolios into apparent indecision.'),
      n('assume2', 'Worth must be proven', 350, 430, 2, 'rule', 'An assumption that converts social recognition into a proxy for meaning.'),
      n('assume3', 'Security must come first', 550, 430, 2, 'rule', 'A priority rule that can make exploration perpetually premature.'),
      n('assume4', 'Realistic = socially familiar', 750, 430, 2, 'rule', 'A rule that deletes unfamiliar possibilities before evaluation.'),
      n('assume5', 'Identity should stay coherent', 950, 430, 2, 'rule', 'A rule penalising beginnerhood and identity transition.'),
      n('objective', 'Hidden objective: avoid shame / regret', 280, 610, 3, 'rule', 'The system may claim to optimise purpose while actually optimising emotional self-protection.'),
      n('reward', 'Reward function: prestige + certainty', 550, 610, 3, 'rule', 'What the environment repeatedly rewards becomes confused with what matters.'),
      n('prohibit', 'Prohibition: do not look foolish', 820, 610, 3, 'rule', 'A social-emotional prohibition that removes exploratory actions.'),
      n('rewrite1', 'NEW RULE: purpose is a revisable portfolio', 245, 715, 4, 'rule', 'A redesigned generator that permits multiple simultaneous expressions.'),
      n('rewrite2', 'NEW RULE: experiments buy information', 550, 715, 4, 'rule', 'A rule that treats uncertainty as a reason to experiment rather than freeze.'),
      n('rewrite3', 'NEW RULE: worth ≠ outcome', 855, 715, 4, 'rule', 'Separating worth from performance changes the emotional cost of exploration.'),
      n('newspace', 'NEW POSSIBILITY SPACE', 550, 835, 4, 'trajectory', 'A regenerated option landscape containing combinations previously excluded.'),
    ],
    edges: [
      e('visible', 'career', 'currently contains', 1, 'Visible trajectory.'),
      e('visible', 'portfolio', 'currently contains', 1, 'Visible trajectory.'),
      e('visible', 'service', 'currently contains', 1, 'Visible trajectory.'),
      e('visible', 'explore', 'currently contains', 1, 'Visible trajectory.'),
      e('assume1', 'career', 'privileges', 2, 'The “one thing” rule makes single-career coherence look superior.'),
      e('assume1', 'portfolio', 'delegitimises', 2, 'The same rule makes a portfolio look like failure to choose.', { tension: true }),
      e('assume2', 'career', 'loads status into', 2, 'Worth-proving biases the trajectory toward legible achievement.'),
      e('assume3', 'explore', 'delays', 2, 'Security-first logic can indefinitely postpone exploration.', { tension: true }),
      e('assume4', 'visible', 'filters', 2, 'Familiarity determines which futures enter awareness.'),
      e('assume5', 'explore', 'penalises identity change in', 2, 'Identity-coherence increases the cost of beginnerhood.'),
      e('objective', 'assume2', 'drives', 3, 'Avoiding shame can create the worth-proving rule.'),
      e('reward', 'visible', 'ranks', 3, 'Prestige and certainty rank visible options before conscious deliberation.'),
      e('prohibit', 'explore', 'excludes', 3, 'Fear of looking foolish deletes experiments.'),
      e('rewrite1', 'portfolio', 'legitimises', 4, 'Rule change alters the interpretation of an existing future.'),
      e('rewrite2', 'explore', 'makes rational', 4, 'Experimentation becomes a method rather than indecision.'),
      e('rewrite3', 'objective', 'weakens', 4, 'Decoupling worth from outcome reduces shame optimisation.'),
      e('rewrite1', 'newspace', 'generates', 4, 'New rules create new options.'),
      e('rewrite2', 'newspace', 'generates', 4, 'New rules create new options.'),
      e('rewrite3', 'newspace', 'generates', 4, 'New rules create new options.'),
    ],
  },
  {
    level: 7,
    title: 'Life Purpose translated across coherent frameworks',
    thesis: 'Purpose is not one concept viewed more carefully. Different frameworks define the object itself differently. Learn to inhabit, translate and compare several coherent maps.',
    blindSpot: '6D can rewrite rules while remaining inside one ontology. A rule that looks irrational in one framework may be sensible in another.',
    leap: '7D models multiple rule-generating frameworks, translates vocabulary between them, locates true incompatibilities and seeks integrations that preserve useful distinctions.',
    question: 'What does “life purpose” become when the underlying philosophy of personhood, value and reality changes?',
    stages: ['Construct distinct frameworks', 'State each framework’s purpose definition', 'Translate equivalent functions', 'Map incompatibilities and integration'],
    insights: [
      'Existentialism asks what commitment you author under freedom; eudaimonia asks what form of life develops excellences; self-determination asks what satisfies autonomy, competence and relatedness.',
      'An ecological frame expands the unit of analysis from individual fulfilment to participation in living systems.',
      'A transpersonal frame may treat purpose as alignment with something larger than the autobiographical self, while an economic frame asks how scarce capabilities create value.',
      'Integration should not flatten disagreements. It can treat each framework as answering a different layer of the purpose problem.',
    ],
    nodes: [
      n('purpose', 'LIFE PURPOSE', 550, 90, 1, 'focus', 'The same phrase interpreted by different ontologies.'),
      n('exist', 'Existential', 120, 285, 1, 'framework', 'Purpose is authored commitment under freedom, finitude and responsibility.'),
      n('eud', 'Eudaimonic', 330, 285, 1, 'framework', 'Purpose is part of living well through developed excellences and worthy activity.'),
      n('sdt', 'Self-Determination', 550, 285, 1, 'framework', 'Purpose is sustainable when autonomy, competence and relatedness are supported.'),
      n('eco', 'Ecological / Systems', 770, 285, 1, 'framework', 'Purpose is a role in maintaining or regenerating systems larger than the individual.'),
      n('trans', 'Transpersonal', 980, 285, 1, 'framework', 'Purpose is alignment with a reality, value or consciousness larger than ego identity.'),
      n('economic', 'Economic / Vocational', 220, 500, 2, 'framework', 'Purpose is partly where valuable capability meets real demand under constraints.'),
      n('narrative', 'Narrative Identity', 440, 500, 2, 'framework', 'Purpose is a story that organises past, present and anticipated contribution.'),
      n('evolution', 'Evolutionary', 660, 500, 2, 'framework', 'Purpose-like motivations are interpreted through survival, affiliation, status, care and generativity.'),
      n('translation', 'TRANSLATION LAYER', 880, 500, 3, 'framework', 'Translate function before comparing words: calling ↔ commitment ↔ valued role ↔ organising narrative.'),
      n('conflict', 'INCOMPATIBILITIES', 350, 690, 4, 'framework', 'Some claims cannot all be literal at once: discovered cosmic purpose versus wholly authored purpose, for example.'),
      n('integration', 'INTEGRATED META-FRAME', 750, 690, 4, 'framework', 'Treat purpose as authored + embodied + relational + ecological + revisable, while keeping metaphysical claims explicitly separate.'),
      n('test', 'Frame-switch Test', 550, 830, 4, 'factor', 'If a conclusion survives several frameworks for different reasons, it may be unusually robust.'),
    ],
    edges: [
      e('purpose', 'exist', 'means', 1, 'Existential definition.'),
      e('purpose', 'eud', 'means', 1, 'Eudaimonic definition.'),
      e('purpose', 'sdt', 'means', 1, 'Self-determination definition.'),
      e('purpose', 'eco', 'means', 1, 'Ecological definition.'),
      e('purpose', 'trans', 'means', 1, 'Transpersonal definition.'),
      e('purpose', 'economic', 'can mean', 2, 'Vocational-economic definition.'),
      e('purpose', 'narrative', 'can mean', 2, 'Narrative definition.'),
      e('purpose', 'evolution', 'can be explained by', 2, 'Evolutionary interpretation.'),
      e('exist', 'translation', 'translates commitment into', 3, 'Compare functions across vocabularies.'),
      e('narrative', 'translation', 'translates coherence into', 3, 'Narrative coherence may function similarly to existential commitment without making the same metaphysical claim.'),
      e('economic', 'translation', 'translates contribution into', 3, 'Economic value is one operationalisation of contribution, not the whole concept.'),
      e('trans', 'conflict', 'may conflict with', 4, 'Discovered transcendent purpose can conflict with radical authorship if both are asserted literally.'),
      e('exist', 'conflict', 'may conflict with', 4, 'Genuine incompatibility should be named rather than blurred.'),
      e('eud', 'integration', 'contributes flourishing', 4, 'Keep the eudaimonic insight.'),
      e('sdt', 'integration', 'contributes psychological sustainability', 4, 'Keep the motivational insight.'),
      e('eco', 'integration', 'contributes system scale', 4, 'Keep the ecological expansion of beneficiary and consequence.'),
      e('narrative', 'integration', 'contributes temporal coherence', 4, 'Keep the narrative function.'),
      e('integration', 'test', 'is stress-tested by', 4, 'A meta-frame must remain open to disconfirmation.'),
    ],
  },
  {
    level: 8,
    title: 'Life Purpose rotated through observers and scales',
    thesis: 'Make the observer an explicit variable. The same purpose pursuit can look noble, selfish, costly, necessary or invisible depending on standpoint, scale and time horizon.',
    blindSpot: '7D compares conceptual frameworks but can still speak as though there is one neutral view from nowhere.',
    leap: '8D rotates the observer and tracks reflexivity: who sees what, who bears costs, what scale changes meaning, and how being observed changes behaviour.',
    question: 'How does my proposed life purpose change when seen by every materially affected observer—from present self to future generations?',
    stages: ['Place the phenomenon at centre', 'Rotate human observers', 'Change scale', 'Add blind spots and observer effects'],
    insights: [
      'Current self may experience a risky career shift as liberation; future self may see lost compounding or regret; a partner may see altered financial exposure.',
      'Beneficiaries can judge contribution by usefulness rather than by how meaningful it feels to the contributor.',
      'Species and planetary perspectives can invert the ranking of high-status but extractive work.',
      'Publicly declaring a purpose can create commitment and accountability while also corrupting exploration through identity performance.',
    ],
    nodes: [
      n('purpose', 'Life Purpose Pursuit', 550, 390, 1, 'focus', 'The observed phenomenon.'),
      n('present', 'Present Self', 550, 90, 2, 'observer', 'Sees immediate aliveness, fear and opportunity cost.'),
      n('future', 'Future Self (20y)', 835, 150, 2, 'observer', 'Sees compounding, regret, health and identity consequences.'),
      n('partner', 'Partner / Family', 1010, 350, 2, 'observer', 'Sees shared risk, time allocation, dependability and relational presence.'),
      n('beneficiary', 'Beneficiaries', 900, 610, 2, 'observer', 'Judge whether contribution actually helps rather than whether it feels meaningful.'),
      n('community', 'Community', 650, 710, 2, 'observer', 'Sees externalities, trust, reciprocity and local social effects.'),
      n('outsider', 'Excluded / Harmed Outsider', 400, 710, 2, 'observer', 'Reveals costs that beneficiaries or insiders may not notice.'),
      n('institution', 'Employer / Institution', 180, 610, 2, 'observer', 'Sees reliability, value production, incentives and replaceability.'),
      n('child', 'Child / Next Generation', 90, 350, 2, 'observer', 'Sees what norms, resources and world conditions are inherited.'),
      n('species', 'Species Scale', 235, 150, 3, 'observer', 'Reframes purpose through long-run human coordination and survival.'),
      n('planet', 'Planetary / Ecological Scale', 550, 820, 3, 'observer', 'Tracks ecological externalities invisible at personal scale.'),
      n('blind', 'Observer Blind Spots', 335, 390, 4, 'factor', 'Each standpoint systematically cannot see some information.'),
      n('effect', 'Observer Effect', 765, 390, 4, 'factor', 'The pursuit changes when measured, judged, branded or publicly declared.'),
    ],
    edges: [
      e('present', 'purpose', 'experiences as', 2, 'Present-self perspective.'),
      e('future', 'purpose', 'evaluates consequences of', 2, 'Future-self perspective.'),
      e('partner', 'purpose', 'shares costs of', 2, 'Relational perspective.'),
      e('beneficiary', 'purpose', 'tests usefulness of', 2, 'Beneficiary perspective.'),
      e('community', 'purpose', 'absorbs local effects of', 2, 'Community perspective.'),
      e('outsider', 'purpose', 'reveals hidden costs of', 2, 'Excluded observers expose externalities.'),
      e('institution', 'purpose', 'rewards / constrains', 2, 'Institutional perspective.'),
      e('child', 'purpose', 'inherits consequences of', 2, 'Intergenerational perspective.'),
      e('species', 'purpose', 'changes meaning of', 3, 'Species scale alters the unit of value.'),
      e('planet', 'purpose', 'changes meaning of', 3, 'Planetary scale makes ecological effects morally salient.'),
      e('present', 'blind', 'cannot fully see', 4, 'Immediate emotion hides long-run effects.'),
      e('institution', 'blind', 'cannot fully see', 4, 'Organisational metrics may miss meaning and externalities.'),
      e('purpose', 'effect', 'changes when observed through', 4, 'Measurement and public identity alter behaviour.'),
      e('effect', 'present', 'feeds identity performance back into', 4, 'Public commitment can make updating harder.'),
      e('outsider', 'community', 'challenges consensus of', 4, 'A community can agree while exporting costs elsewhere.', { tension: true }),
      e('future', 'present', 'reframes', 4, 'Future-self simulation changes present evaluation.', { bidirectional: true }),
    ],
  },
  {
    level: 9,
    title: 'Life Purpose as an evolving ecology of models',
    thesis: 'The frameworks themselves now change. Track competing models of purpose as evidence selects, revises, combines or protects them.',
    blindSpot: '8D can rotate perspectives while assuming each perspective’s interpretive model is stable.',
    leap: '9D makes models evolutionary objects: they update, compete for attention, reinterpret anomalies, merge, persist through identity defence or disappear.',
    question: 'Which model of purpose am I using, what evidence would update it, and how might that model protect itself from being wrong?',
    stages: ['Name competing models', 'Feed them evidence', 'Expose model immunity', 'Track revision, selection and invariants'],
    insights: [
      '“One true calling” and “experimental portfolio” can interpret the same boredom differently: betrayal of calling versus information about fit.',
      'A self-sealing purpose model can reinterpret every failure as a test and every success as confirmation; that is psychologically powerful but epistemically weak.',
      'Models are selected not only for truth but for emotional comfort, social reward and cognitive simplicity.',
      'An invariant such as “sustained meaningful contribution matters” may survive even as the explanatory model changes radically.',
    ],
    nodes: [
      n('evidence', 'Lived Evidence', 550, 80, 1, 'factor', 'Experience, outcomes, emotion, impact, contradiction and longitudinal data.'),
      n('calling', 'Model A: One True Calling', 130, 300, 1, 'model', 'Purpose exists as a discoverable singular vocation.'),
      n('fit', 'Model B: Person–Environment Fit', 340, 300, 1, 'model', 'Purpose emerges when traits, values and environment fit well.'),
      n('narrative', 'Model C: Narrative Identity', 550, 300, 1, 'model', 'Purpose is an organising life story that can be rewritten.'),
      n('portfolio', 'Model D: Experimental Portfolio', 760, 300, 1, 'model', 'Purpose is iteratively constructed through parallel experiments.'),
      n('systems', 'Model E: Systems Contribution', 970, 300, 1, 'model', 'Purpose is a useful role within systems and beneficiaries larger than self.'),
      n('anomaly', 'Anomalies', 240, 515, 2, 'factor', 'Evidence each model has difficulty explaining.'),
      n('prediction', 'Predictions', 460, 515, 2, 'factor', 'What should happen next if a model is useful.'),
      n('comfort', 'Emotional Comfort', 680, 515, 2, 'factor', 'Models can survive because they regulate anxiety, not because they predict well.'),
      n('social', 'Social Selection', 900, 515, 2, 'factor', 'Cultures and institutions reward some purpose models more than others.'),
      n('immunity', 'Self-sealing Immunity', 310, 700, 3, 'model', 'A model rewrites disconfirming evidence so that nothing can count against it.'),
      n('update', 'Model Update / Hybridisation', 610, 700, 4, 'model', 'Useful pieces combine while failed assumptions are removed.'),
      n('invariant', 'Invariant: meaningful contribution + vitality + reality contact', 880, 700, 4, 'model', 'A structure that remains valuable across several model revisions.'),
    ],
    edges: [
      e('evidence', 'calling', 'tests', 2, 'Evidence should be allowed to challenge the calling model.'),
      e('evidence', 'fit', 'tests', 2, 'Experience tests fit.'),
      e('evidence', 'narrative', 'tests', 2, 'Narrative coherence is tested by whether it supports reality-based action.'),
      e('evidence', 'portfolio', 'tests', 2, 'Experiment outcomes update portfolio allocation.'),
      e('evidence', 'systems', 'tests', 2, 'Beneficiary and systems impact test contribution.'),
      e('calling', 'anomaly', 'struggles with', 2, 'Multiple equally meaningful roles are an anomaly for singular calling.'),
      e('portfolio', 'prediction', 'generates', 2, 'Portfolio model predicts learning from small experiments.'),
      e('systems', 'prediction', 'generates', 2, 'Systems model predicts purpose should track real contribution better than self-report alone.'),
      e('comfort', 'calling', 'can select for', 3, 'Certainty can make singular-calling models attractive.'),
      e('social', 'fit', 'can select for', 3, 'Institutional categories reward legible fit.'),
      e('calling', 'immunity', 'can protect itself through', 3, '“Failure means I have not found it yet” can make disconfirmation impossible.'),
      e('immunity', 'evidence', 'reclassifies', 3, 'Self-sealing logic prevents evidence from updating the model.', { tension: true }),
      e('anomaly', 'update', 'forces', 4, 'Anomalies should drive model revision.'),
      e('prediction', 'update', 'calibrates', 4, 'Prediction accuracy selects useful model components.'),
      e('update', 'invariant', 'retains', 4, 'Revision can preserve robust structures without preserving the original explanation.'),
      e('invariant', 'evidence', 'stays accountable to', 4, 'Even an invariant remains provisional and reality-tested.'),
    ],
  },
  {
    level: 10,
    title: 'Life Purpose as a deliberately engineered learning architecture',
    thesis: 'Stop waiting for better insight. Design an architecture that repeatedly generates better purpose models, better experiments and better decisions.',
    blindSpot: '9D can understand model evolution without ensuring the environment actually rewards updating rather than certainty, image or inertia.',
    leap: '10D redesigns objectives, inputs, feedback loops, interfaces, constraints, governance and trade-offs so useful purpose discovery becomes more likely by construction.',
    question: 'What personal operating system would reliably make my purpose model more accurate, alive and useful over the next decade?',
    stages: ['Define architecture objectives', 'Build sensing and experiment loops', 'Add governance and constraints', 'Expose trade-offs and failure modes'],
    insights: [
      'Optimise for calibrated aliveness + contribution + sustainability, not for feeling certain.',
      'Maintain a portfolio of purpose experiments with explicit hypotheses, beneficiaries, costs and review dates.',
      'Use anti-self-deception governance: precommit what evidence would cause continuation, redesign or abandonment.',
      'Architecture has trade-offs: more measurement can improve calibration while crowding out spontaneity or intrinsic meaning.',
    ],
    nodes: [
      n('architecture', 'PURPOSE LEARNING ARCHITECTURE', 550, 80, 1, 'architecture', 'The system intentionally designed to generate and revise purpose.'),
      n('objective', 'Objective Function', 170, 220, 1, 'architecture', 'Optimise meaningful contribution, vitality, integrity and sustainability—not certainty.'),
      n('sensors', 'Sensors', 390, 220, 1, 'architecture', 'Energy, attention, learning rate, beneficiary feedback, health, regret and opportunity signals.'),
      n('portfolio', 'Experiment Portfolio', 710, 220, 1, 'architecture', 'Several bounded experiments rather than one all-or-nothing bet.'),
      n('constraints', 'Hard Constraints', 930, 220, 1, 'architecture', 'Health, dependants, money, ethics and non-negotiable obligations.'),
      n('hypothesis', 'Purpose Hypotheses', 200, 425, 2, 'model', 'Explicit claims about what activities, beneficiaries and structures may fit.'),
      n('action', '30–90 day Experiments', 420, 425, 2, 'factor', 'Low-cost actions designed to produce discriminating evidence.'),
      n('feedback', 'Feedback Capture', 650, 425, 2, 'factor', 'Record predicted versus actual energy, impact, skill growth and costs.'),
      n('review', 'Quarterly Review', 880, 425, 2, 'architecture', 'Compare hypotheses, update allocations and look for drift.'),
      n('adversary', 'Adversarial Review', 160, 620, 3, 'architecture', 'Ask what evidence you are motivated not to see.'),
      n('beneficiary', 'Beneficiary Voice', 380, 620, 3, 'architecture', 'Include people affected by the work rather than only the seeker’s feelings.'),
      n('stop', 'Stop / Pivot Rules', 610, 620, 3, 'architecture', 'Predefined conditions for ending or redesigning an experiment.'),
      n('governance', 'Meta-governance', 850, 620, 3, 'architecture', 'Periodically review whether the architecture itself is producing distortions.'),
      n('tradeoff1', 'Measurement ↔ Spontaneity', 260, 800, 4, 'factor', 'More measurement can crowd out intrinsic motivation.'),
      n('tradeoff2', 'Exploration ↔ Compounding', 550, 800, 4, 'factor', 'Too much exploration prevents mastery; too little creates lock-in.'),
      n('tradeoff3', 'Service ↔ Self-maintenance', 840, 800, 4, 'factor', 'Contribution that destroys the contributor is not sustainable architecture.'),
    ],
    edges: [
      e('architecture', 'objective', 'optimises through', 1, 'Objectives define what the architecture rewards.'),
      e('architecture', 'sensors', 'observes through', 1, 'Sensors determine what can be learned.'),
      e('architecture', 'portfolio', 'allocates through', 1, 'Portfolio design distributes exploration.'),
      e('architecture', 'constraints', 'operates within', 1, 'Constraints stop purpose from becoming fantasy.'),
      e('sensors', 'hypothesis', 'inform', 2, 'Signals generate or revise hypotheses.'),
      e('hypothesis', 'action', 'is tested by', 2, 'Hypotheses must create discriminating experiments.'),
      e('action', 'feedback', 'generates', 2, 'Action creates evidence.'),
      e('feedback', 'review', 'feeds', 2, 'Evidence is compared over time.'),
      e('review', 'portfolio', 'reallocates', 2, 'Better-supported paths receive more investment.'),
      e('adversary', 'review', 'challenges', 3, 'Adversarial review reduces motivated reasoning.'),
      e('beneficiary', 'feedback', 'grounds', 3, 'Contribution requires external evidence.'),
      e('stop', 'action', 'governs', 3, 'Stop rules limit sunk-cost lock-in.'),
      e('governance', 'architecture', 'can redesign', 3, 'The architecture itself remains revisable.'),
      e('architecture', 'tradeoff1', 'must manage', 4, 'Architecture has costs.'),
      e('architecture', 'tradeoff2', 'must manage', 4, 'Architecture has costs.'),
      e('architecture', 'tradeoff3', 'must manage', 4, 'Architecture has costs.'),
      e('tradeoff2', 'portfolio', 'sets exploration rate for', 4, 'Portfolio size should balance learning with compounding.'),
      e('tradeoff3', 'objective', 'prevents pathological', 4, 'Sustainability constrains service optimisation.'),
    ],
  },
  {
    level: 11,
    title: 'Life Purpose inside co-evolving adaptive architectures',
    thesis: 'Your purpose architecture is not alone. Family, culture, labour markets, technology, institutions and ecosystems are adaptive systems that change in response to one another.',
    blindSpot: '10D can design an excellent personal system as though the surrounding systems were static background conditions.',
    leap: '11D tracks recursive co-adaptation, emergent incentives, arms races, cooperation and meta-stability across several possibility-generating architectures.',
    question: 'How does my pursuit of purpose change the systems around me—and how do their adaptations then change who I can become?',
    stages: ['Name adaptive systems', 'Map reciprocal adaptations', 'Identify emergence and unintended incentives', 'Find stabilisers and leverage points'],
    insights: [
      'A person enters a meaningful profession; the profession rewards visible metrics; the person adapts to metrics; aggregated adaptation changes the profession itself.',
      'Family expectations respond to career risk, which changes the person’s behaviour, which changes family trust and future permission structures.',
      'AI can automate tasks, changing labour-market rewards, which changes educational investment, identity and the kinds of contribution that remain scarce.',
      'Purpose at 11D becomes partly governance: designing relationships among adaptive systems so no single system’s incentive destroys the whole.',
    ],
    nodes: [
      n('self', 'Personal Purpose System', 550, 380, 1, 'system', 'Identity, habits, learning loops, values and chosen experiments.'),
      n('family', 'Family System', 160, 170, 1, 'system', 'Expectations, care obligations, risk sharing and inherited narratives.'),
      n('culture', 'Culture / Status System', 550, 100, 1, 'system', 'Shared prestige signals, moral narratives and definitions of success.'),
      n('market', 'Labour Market', 940, 170, 1, 'system', 'Prices skills, creates scarcity and rewards particular roles.'),
      n('tech', 'Technology / AI', 1020, 470, 1, 'system', 'Changes capability, substitution, coordination costs and opportunity.'),
      n('institution', 'Institutions', 820, 735, 1, 'system', 'Professional rules, credentials, organisations and governance.'),
      n('ecology', 'Ecological System', 550, 820, 1, 'system', 'Material and biological conditions affected by production and consumption.'),
      n('community', 'Community', 275, 735, 1, 'system', 'Local trust, reciprocity, needs and informal opportunity structures.'),
      n('health', 'Body / Health System', 80, 470, 1, 'system', 'Adaptive biological limits and capacities that respond to workload.'),
      n('metric', 'Metric Optimisation', 330, 310, 2, 'factor', 'Systems adapt to what is measured, sometimes destroying the intended value.'),
      n('automation', 'Automation Response', 790, 310, 2, 'factor', 'Technology changes what skills remain scarce and meaningful.'),
      n('norm', 'Norm Shift', 400, 590, 2, 'factor', 'Enough individual adaptations can alter cultural expectations.'),
      n('emergence', 'EMERGENT PURPOSE LANDSCAPE', 700, 590, 3, 'system', 'The opportunity field nobody individually designed.'),
      n('governance', 'Cross-system Governance', 550, 665, 4, 'architecture', 'Rules that keep local optimisation from destroying shared long-run value.'),
      n('stability', 'Meta-stability: truth + reciprocity + ecological viability', 550, 940, 4, 'system', 'Conditions that allow several adaptive systems to change without runaway degradation.'),
    ],
    edges: [
      e('family', 'self', 'co-adapts with', 2, 'Risk-taking changes family expectations; expectations change risk-taking.', { bidirectional: true }),
      e('culture', 'self', 'selects identities in', 2, 'Culture rewards legible purpose narratives.'),
      e('market', 'self', 'prices capabilities of', 2, 'Economic reward changes feasible purpose expressions.'),
      e('tech', 'market', 'reshapes scarcity in', 2, 'Automation changes labour demand.'),
      e('market', 'tech', 'funds development of', 2, 'Market incentives also steer technology.', { bidirectional: true }),
      e('institution', 'market', 'regulates', 2, 'Institutions alter economic incentives.'),
      e('self', 'health', 'loads', 2, 'Work patterns change the body.'),
      e('health', 'self', 'constrains', 2, 'The body changes viable purpose.', { bidirectional: true }),
      e('self', 'community', 'contributes to', 2, 'Purpose pursuit alters local social capital.'),
      e('community', 'self', 'creates opportunities for', 2, 'Community needs and relationships create purpose options.', { bidirectional: true }),
      e('culture', 'metric', 'creates prestige metrics that drive', 2, 'Status systems create optimisation pressure.'),
      e('metric', 'self', 'changes behaviour of', 2, 'People adapt to metrics.'),
      e('self', 'norm', 'aggregates into', 2, 'Many individual choices can shift norms.'),
      e('norm', 'culture', 'rewrites', 2, 'Norm shifts change culture, closing the loop.'),
      e('tech', 'automation', 'produces', 2, 'Technology produces substitution pressure.'),
      e('automation', 'self', 'forces reskilling / reframing in', 2, 'Automation changes personal purpose possibilities.'),
      e('self', 'emergence', 'co-produces', 3, 'Individual adaptation contributes to an emergent landscape.'),
      e('family', 'emergence', 'co-produces', 3, 'Family strategies aggregate into social opportunity patterns.'),
      e('market', 'emergence', 'co-produces', 3, 'Market dynamics shape the landscape.'),
      e('tech', 'emergence', 'co-produces', 3, 'Technology shapes the landscape.'),
      e('institution', 'emergence', 'co-produces', 3, 'Rules shape the landscape.'),
      e('ecology', 'emergence', 'constrains', 3, 'Physical systems ultimately constrain the landscape.'),
      e('emergence', 'self', 'selects future identities in', 3, 'The emergent landscape feeds back into the person.'),
      e('governance', 'metric', 'limits gaming of', 4, 'Governance can realign metrics with intended value.'),
      e('governance', 'market', 'changes incentives in', 4, 'Governance alters adaptive pressures.'),
      e('governance', 'ecology', 'protects viability of', 4, 'Long-term purpose requires material viability.'),
      e('stability', 'governance', 'is maintained by', 4, 'Meta-stability depends on governance that can itself adapt.'),
      e('ecology', 'stability', 'sets hard boundary for', 4, 'No purpose architecture escapes ecological reality.'),
    ],
  },
  {
    level: 12,
    title: 'Life Purpose remapped by inventing new dimensions',
    thesis: 'Question the representational axes themselves. Invent distinctions that make previously collapsed differences visible, then test what those new dimensions reveal and hide.',
    blindSpot: '11D can model astonishing complexity while still accepting the coordinate system in which the complexity is represented.',
    leap: '12D treats dimensionality as designable. The learner creates new axes, remaps options through them, identifies representational costs and states what evidence would force the axes themselves to change.',
    question: 'What is currently impossible to think about Life Purpose because my map lacks the dimension needed to represent it?',
    stages: ['Expose inherited axes', 'Invent new representational dimensions', 'Remap life options', 'Test blind spots and recursively revise the axes'],
    insights: [
      '“Successful versus unsuccessful” collapses radically different futures. Add recoverability and a failed experiment may outrank a prestigious irreversible commitment.',
      'Add beneficiary radius and two equally meaningful careers separate by who actually receives value—self, family, community, species or ecosystem.',
      'Add temporal depth and a choice can be personally costly now yet generative across decades or generations.',
      'Every new axis creates new blindness. Quantifying “generativity” may erase irreducible qualities, so the representation itself needs a revision rule.',
    ],
    nodes: [
      n('purpose', 'LIFE PURPOSE SPACE', 550, 90, 1, 'focus', 'The problem space whose coordinate system is now questioned.'),
      n('old1', 'Inherited axis: success ↔ failure', 250, 230, 1, 'axis', 'A common but low-resolution representation.'),
      n('old2', 'Inherited axis: meaningful ↔ meaningless', 550, 230, 1, 'axis', 'Another binary that collapses different mechanisms.'),
      n('old3', 'Inherited axis: self ↔ others', 850, 230, 1, 'axis', 'A binary that misses nested beneficiary scales.'),
      n('recover', 'NEW AXIS: Recoverability', 120, 430, 2, 'axis', 'How easily can a choice be reversed after new information arrives?'),
      n('radius', 'NEW AXIS: Beneficiary Radius', 335, 430, 2, 'axis', 'How far from self do benefits and costs propagate?'),
      n('temporal', 'NEW AXIS: Temporal Depth', 550, 430, 2, 'axis', 'Over what time horizon does the purpose create or destroy value?'),
      n('generative', 'NEW AXIS: Generativity', 765, 430, 2, 'axis', 'Does the path create capabilities and options for future agents?'),
      n('epistemic', 'NEW AXIS: Epistemic Exposure', 980, 430, 2, 'axis', 'How strongly does the path expose itself to evidence that could prove it wrong?'),
      n('identity', 'NEW AXIS: Identity Permeability', 225, 610, 2, 'axis', 'Can the person change identity without treating revision as betrayal?'),
      n('embody', 'NEW AXIS: Embodiment', 445, 610, 2, 'axis', 'How compatible is the path with nervous system, health and lived bodily reality?'),
      n('interdep', 'NEW AXIS: Interdependence', 665, 610, 2, 'axis', 'How accurately does the path represent dependence on people and systems?'),
      n('renew', 'NEW AXIS: Regenerative Capacity', 885, 610, 2, 'axis', 'Does the activity replenish or deplete the systems that support it?'),
      n('optionA', 'Option A: prestigious specialist role', 180, 800, 3, 'trajectory', 'High status and mastery, potentially low recoverability and narrow beneficiary radius.'),
      n('optionB', 'Option B: experimental portfolio', 420, 800, 3, 'trajectory', 'High recoverability and epistemic exposure, lower short-term compounding.'),
      n('optionC', 'Option C: community institution builder', 680, 800, 3, 'trajectory', 'High generativity and beneficiary radius, high coordination burden.'),
      n('optionD', 'Option D: ecological stewardship', 930, 800, 3, 'trajectory', 'Long temporal depth and regenerative ambition, possibly low immediate reward.'),
      n('cost', 'REPRESENTATIONAL COST', 350, 980, 4, 'axis', 'New axes can create false precision, omit qualitative meaning or privilege what is measurable.'),
      n('revision', 'AXIS REVISION RULE', 750, 980, 4, 'axis', 'If an axis repeatedly predicts poorly, depends on observer, or hides decisive qualities, split, merge or remove it.'),
    ],
    edges: [
      e('purpose', 'old1', 'was previously represented by', 1, 'Inherited coordinate.'),
      e('purpose', 'old2', 'was previously represented by', 1, 'Inherited coordinate.'),
      e('purpose', 'old3', 'was previously represented by', 1, 'Inherited coordinate.'),
      e('purpose', 'recover', 'becomes newly visible through', 2, 'New dimension.'),
      e('purpose', 'radius', 'becomes newly visible through', 2, 'New dimension.'),
      e('purpose', 'temporal', 'becomes newly visible through', 2, 'New dimension.'),
      e('purpose', 'generative', 'becomes newly visible through', 2, 'New dimension.'),
      e('purpose', 'epistemic', 'becomes newly visible through', 2, 'New dimension.'),
      e('purpose', 'identity', 'becomes newly visible through', 2, 'New dimension.'),
      e('purpose', 'embody', 'becomes newly visible through', 2, 'New dimension.'),
      e('purpose', 'interdep', 'becomes newly visible through', 2, 'New dimension.'),
      e('purpose', 'renew', 'becomes newly visible through', 2, 'New dimension.'),
      e('recover', 'optionB', 'raises value of', 3, 'A reversible experiment can look better once recoverability exists as an axis.'),
      e('radius', 'optionC', 'reveals wider effects of', 3, 'Beneficiary radius differentiates community institution building.'),
      e('temporal', 'optionD', 'reveals long-horizon value of', 3, 'Temporal depth changes the ranking of ecological stewardship.'),
      e('generative', 'optionC', 'reveals option creation by', 3, 'Institutions can create possibilities for people not yet present.'),
      e('epistemic', 'optionB', 'reveals learning strength of', 3, 'Experimental portfolios generate discriminating evidence.'),
      e('identity', 'optionA', 'reveals lock-in risk of', 3, 'Prestigious roles can become identity traps despite success.'),
      e('embody', 'optionA', 'tests sustainability of', 3, 'Embodiment exposes paths that look good abstractly but degrade the body.'),
      e('renew', 'optionD', 'tests regenerative effect of', 3, 'Regenerative capacity distinguishes sustainable from extractive contribution.'),
      e('cost', 'recover', 'can distort', 4, 'Every new metric can create gaming or false precision.', { tension: true }),
      e('cost', 'generative', 'can distort', 4, 'Generativity is partly qualitative and observer-dependent.', { tension: true }),
      e('revision', 'cost', 'responds to', 4, 'Representation should contain a mechanism for revising itself.'),
      e('revision', 'purpose', 'reconstitutes the space of', 4, 'At 12D, failure of the coordinate system sends reasoning back to redesign the problem itself.'),
    ],
  },
]

export function getLifePurposeAtlas(level: number): LifePurposeAtlasMap {
  const safe = Math.max(1, Math.min(12, Math.round(level))) as AtlasLevel
  return LIFE_PURPOSE_ATLAS[safe - 1]
}
